package models

import "github.com/invopop/jsonschema"

// BlueprintJSONSchema returns the JSON Schema describing the shape of a
// blueprint's YAML/JSON representation, as returned by k8shelld's
// GetBlueprint RPC. It's generated by reflecting over Blueprint's json tags
// so it always mirrors the field names that representation actually uses.
func BlueprintJSONSchema() *jsonschema.Schema {
	r := &jsonschema.Reflector{ExpandedStruct: true}
	return r.Reflect(&Blueprint{})
}
