// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: pkg/gapi/common.proto

package commonpb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Organization  string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	IsValid       bool                   `protobuf:"varint,3,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	ExpiresAt     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Uid           uint32                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,6,opt,name=gid,proto3" json:"gid,omitempty"`
	Fullname      string                 `protobuf:"bytes,7,opt,name=fullname,proto3" json:"fullname,omitempty"`
	AccessToken   string                 `protobuf:"bytes,8,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Email         string                 `protobuf:"bytes,9,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,10,opt,name=password,proto3" json:"password,omitempty"`
	Auths         []string               `protobuf:"bytes,11,rep,name=auths,proto3" json:"auths,omitempty"`
	AuthKeys      []string               `protobuf:"bytes,12,rep,name=auth_keys,json=authKeys,proto3" json:"auth_keys,omitempty"`
	Locked        bool                   `protobuf:"varint,13,opt,name=locked,proto3" json:"locked,omitempty"`
	FailedLogins  uint32                 `protobuf:"varint,14,opt,name=failed_logins,json=failedLogins,proto3" json:"failed_logins,omitempty"`
	Channels      []string               `protobuf:"bytes,15,rep,name=channels,proto3" json:"channels,omitempty"`
	Envs          []string               `protobuf:"bytes,16,rep,name=envs,proto3" json:"envs,omitempty"`
	Roles         []string               `protobuf:"bytes,17,rep,name=roles,proto3" json:"roles,omitempty"`
	Blueprints    []string               `protobuf:"bytes,18,rep,name=blueprints,proto3" json:"blueprints,omitempty"`
	Source        string                 `protobuf:"bytes,19,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_pkg_gapi_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *User) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *User) GetExpiresAt() *timestamp.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *User) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *User) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *User) GetFullname() string {
	if x != nil {
		return x.Fullname
	}
	return ""
}

func (x *User) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetAuths() []string {
	if x != nil {
		return x.Auths
	}
	return nil
}

func (x *User) GetAuthKeys() []string {
	if x != nil {
		return x.AuthKeys
	}
	return nil
}

func (x *User) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *User) GetFailedLogins() uint32 {
	if x != nil {
		return x.FailedLogins
	}
	return 0
}

func (x *User) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *User) GetEnvs() []string {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetBlueprints() []string {
	if x != nil {
		return x.Blueprints
	}
	return nil
}

func (x *User) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ExternalCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceUrl    string                 `protobuf:"bytes,4,opt,name=service_url,json=serviceUrl,proto3" json:"service_url,omitempty"`
	ExternalId    string                 `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ExternalToken string                 `protobuf:"bytes,6,opt,name=external_token,json=externalToken,proto3" json:"external_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalCredential) Reset() {
	*x = ExternalCredential{}
	mi := &file_pkg_gapi_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalCredential) ProtoMessage() {}

func (x *ExternalCredential) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalCredential.ProtoReflect.Descriptor instead.
func (*ExternalCredential) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{1}
}

func (x *ExternalCredential) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ExternalCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExternalCredential) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ExternalCredential) GetServiceUrl() string {
	if x != nil {
		return x.ServiceUrl
	}
	return ""
}

func (x *ExternalCredential) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ExternalCredential) GetExternalToken() string {
	if x != nil {
		return x.ExternalToken
	}
	return ""
}

type OnboardUserDeviceFlow struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Provider        string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Username        string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	UserCode        string                 `protobuf:"bytes,3,opt,name=user_code,json=userCode,proto3" json:"user_code,omitempty"`
	VerificationUrl string                 `protobuf:"bytes,4,opt,name=verification_url,json=verificationUrl,proto3" json:"verification_url,omitempty"`
	ExpiresIn       int32                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnboardUserDeviceFlow) Reset() {
	*x = OnboardUserDeviceFlow{}
	mi := &file_pkg_gapi_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnboardUserDeviceFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnboardUserDeviceFlow) ProtoMessage() {}

func (x *OnboardUserDeviceFlow) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnboardUserDeviceFlow.ProtoReflect.Descriptor instead.
func (*OnboardUserDeviceFlow) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{2}
}

func (x *OnboardUserDeviceFlow) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *OnboardUserDeviceFlow) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *OnboardUserDeviceFlow) GetUserCode() string {
	if x != nil {
		return x.UserCode
	}
	return ""
}

func (x *OnboardUserDeviceFlow) GetVerificationUrl() string {
	if x != nil {
		return x.VerificationUrl
	}
	return ""
}

func (x *OnboardUserDeviceFlow) GetExpiresIn() int32 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type UserOnboardCapability struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CanOnboard    bool                   `protobuf:"varint,3,opt,name=can_onboard,json=canOnboard,proto3" json:"can_onboard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOnboardCapability) Reset() {
	*x = UserOnboardCapability{}
	mi := &file_pkg_gapi_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOnboardCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOnboardCapability) ProtoMessage() {}

func (x *UserOnboardCapability) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOnboardCapability.ProtoReflect.Descriptor instead.
func (*UserOnboardCapability) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{3}
}

func (x *UserOnboardCapability) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UserOnboardCapability) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserOnboardCapability) GetCanOnboard() bool {
	if x != nil {
		return x.CanOnboard
	}
	return false
}

// PodStatus represents the status of a workspace pod
type PodStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatus) Reset() {
	*x = PodStatus{}
	mi := &file_pkg_gapi_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatus) ProtoMessage() {}

func (x *PodStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatus.ProtoReflect.Descriptor instead.
func (*PodStatus) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{4}
}

func (x *PodStatus) GetCreated() *timestamp.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *PodStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PodStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// WorkspaceStatus represents the current status of a workspace
type WorkspaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodStatus     *PodStatus             `protobuf:"bytes,1,opt,name=pod_status,json=podStatus,proto3" json:"pod_status,omitempty"`
	AppVersion    string                 `protobuf:"bytes,2,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Host          string                 `protobuf:"bytes,4,opt,name=host,proto3" json:"host,omitempty"`
	PodIp         string                 `protobuf:"bytes,5,opt,name=pod_ip,json=podIp,proto3" json:"pod_ip,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	AccessKey     string                 `protobuf:"bytes,7,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
	TlsCert       string                 `protobuf:"bytes,8,opt,name=tls_cert,json=tlsCert,proto3" json:"tls_cert,omitempty"`
	Splash        string                 `protobuf:"bytes,9,opt,name=splash,proto3" json:"splash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceStatus) Reset() {
	*x = WorkspaceStatus{}
	mi := &file_pkg_gapi_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceStatus) ProtoMessage() {}

func (x *WorkspaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceStatus.ProtoReflect.Descriptor instead.
func (*WorkspaceStatus) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{5}
}

func (x *WorkspaceStatus) GetPodStatus() *PodStatus {
	if x != nil {
		return x.PodStatus
	}
	return nil
}

func (x *WorkspaceStatus) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *WorkspaceStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceStatus) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *WorkspaceStatus) GetPodIp() string {
	if x != nil {
		return x.PodIp
	}
	return ""
}

func (x *WorkspaceStatus) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *WorkspaceStatus) GetAccessKey() string {
	if x != nil {
		return x.AccessKey
	}
	return ""
}

func (x *WorkspaceStatus) GetTlsCert() string {
	if x != nil {
		return x.TlsCert
	}
	return ""
}

func (x *WorkspaceStatus) GetSplash() string {
	if x != nil {
		return x.Splash
	}
	return ""
}

// WorkspaceInfo represents the information of a workspace
type WorkspaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Blueprint     string                 `protobuf:"bytes,3,opt,name=blueprint,proto3" json:"blueprint,omitempty"`
	Deployed      *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=deployed,proto3" json:"deployed,omitempty"`
	AppVersion    string                 `protobuf:"bytes,5,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	Chart         string                 `protobuf:"bytes,6,opt,name=chart,proto3" json:"chart,omitempty"`
	ChartVer      string                 `protobuf:"bytes,7,opt,name=chart_ver,json=chartVer,proto3" json:"chart_ver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkspaceInfo) Reset() {
	*x = WorkspaceInfo{}
	mi := &file_pkg_gapi_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkspaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkspaceInfo) ProtoMessage() {}

func (x *WorkspaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gapi_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkspaceInfo.ProtoReflect.Descriptor instead.
func (*WorkspaceInfo) Descriptor() ([]byte, []int) {
	return file_pkg_gapi_common_proto_rawDescGZIP(), []int{6}
}

func (x *WorkspaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkspaceInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *WorkspaceInfo) GetBlueprint() string {
	if x != nil {
		return x.Blueprint
	}
	return ""
}

func (x *WorkspaceInfo) GetDeployed() *timestamp.Timestamp {
	if x != nil {
		return x.Deployed
	}
	return nil
}

func (x *WorkspaceInfo) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *WorkspaceInfo) GetChart() string {
	if x != nil {
		return x.Chart
	}
	return ""
}

func (x *WorkspaceInfo) GetChartVer() string {
	if x != nil {
		return x.ChartVer
	}
	return ""
}

var File_pkg_gapi_common_proto protoreflect.FileDescriptor

const file_pkg_gapi_common_proto_rawDesc = "" +
	"\n" +
	"\x15pkg/gapi/common.proto\x12\x06common\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x04\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12\x19\n" +
	"\bis_valid\x18\x03 \x01(\bR\aisValid\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x06 \x01(\rR\x03gid\x12\x1a\n" +
	"\bfullname\x18\a \x01(\tR\bfullname\x12!\n" +
	"\faccess_token\x18\b \x01(\tR\vaccessToken\x12\x14\n" +
	"\x05email\x18\t \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\n" +
	" \x01(\tR\bpassword\x12\x14\n" +
	"\x05auths\x18\v \x03(\tR\x05auths\x12\x1b\n" +
	"\tauth_keys\x18\f \x03(\tR\bauthKeys\x12\x16\n" +
	"\x06locked\x18\r \x01(\bR\x06locked\x12#\n" +
	"\rfailed_logins\x18\x0e \x01(\rR\ffailedLogins\x12\x1a\n" +
	"\bchannels\x18\x0f \x03(\tR\bchannels\x12\x12\n" +
	"\x04envs\x18\x10 \x03(\tR\x04envs\x12\x14\n" +
	"\x05roles\x18\x11 \x03(\tR\x05roles\x12\x1e\n" +
	"\n" +
	"blueprints\x18\x12 \x03(\tR\n" +
	"blueprints\x12\x16\n" +
	"\x06source\x18\x13 \x01(\tR\x06source\"\xcc\x01\n" +
	"\x12ExternalCredential\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1f\n" +
	"\vservice_url\x18\x04 \x01(\tR\n" +
	"serviceUrl\x12\x1f\n" +
	"\vexternal_id\x18\x05 \x01(\tR\n" +
	"externalId\x12%\n" +
	"\x0eexternal_token\x18\x06 \x01(\tR\rexternalToken\"\xb6\x01\n" +
	"\x15OnboardUserDeviceFlow\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1b\n" +
	"\tuser_code\x18\x03 \x01(\tR\buserCode\x12)\n" +
	"\x10verification_url\x18\x04 \x01(\tR\x0fverificationUrl\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x05R\texpiresIn\"p\n" +
	"\x15UserOnboardCapability\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1f\n" +
	"\vcan_onboard\x18\x03 \x01(\bR\n" +
	"canOnboard\"s\n" +
	"\tPodStatus\x124\n" +
	"\acreated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x89\x02\n" +
	"\x0fWorkspaceStatus\x120\n" +
	"\n" +
	"pod_status\x18\x01 \x01(\v2\x11.common.PodStatusR\tpodStatus\x12\x1f\n" +
	"\vapp_version\x18\x02 \x01(\tR\n" +
	"appVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04host\x18\x04 \x01(\tR\x04host\x12\x15\n" +
	"\x06pod_ip\x18\x05 \x01(\tR\x05podIp\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"access_key\x18\a \x01(\tR\taccessKey\x12\x19\n" +
	"\btls_cert\x18\b \x01(\tR\atlsCert\x12\x16\n" +
	"\x06splash\x18\t \x01(\tR\x06splash\"\xe9\x01\n" +
	"\rWorkspaceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1c\n" +
	"\tblueprint\x18\x03 \x01(\tR\tblueprint\x126\n" +
	"\bdeployed\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bdeployed\x12\x1f\n" +
	"\vapp_version\x18\x05 \x01(\tR\n" +
	"appVersion\x12\x14\n" +
	"\x05chart\x18\x06 \x01(\tR\x05chart\x12\x1b\n" +
	"\tchart_ver\x18\a \x01(\tR\bchartVerB9Z7github.com/k8shell-io/common/pkg/gapi/commonpb;commonpbb\x06proto3"

var (
	file_pkg_gapi_common_proto_rawDescOnce sync.Once
	file_pkg_gapi_common_proto_rawDescData []byte
)

func file_pkg_gapi_common_proto_rawDescGZIP() []byte {
	file_pkg_gapi_common_proto_rawDescOnce.Do(func() {
		file_pkg_gapi_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_gapi_common_proto_rawDesc), len(file_pkg_gapi_common_proto_rawDesc)))
	})
	return file_pkg_gapi_common_proto_rawDescData
}

var file_pkg_gapi_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_gapi_common_proto_goTypes = []any{
	(*User)(nil),                  // 0: common.User
	(*ExternalCredential)(nil),    // 1: common.ExternalCredential
	(*OnboardUserDeviceFlow)(nil), // 2: common.OnboardUserDeviceFlow
	(*UserOnboardCapability)(nil), // 3: common.UserOnboardCapability
	(*PodStatus)(nil),             // 4: common.PodStatus
	(*WorkspaceStatus)(nil),       // 5: common.WorkspaceStatus
	(*WorkspaceInfo)(nil),         // 6: common.WorkspaceInfo
	(*timestamp.Timestamp)(nil),   // 7: google.protobuf.Timestamp
}
var file_pkg_gapi_common_proto_depIdxs = []int32{
	7, // 0: common.User.expires_at:type_name -> google.protobuf.Timestamp
	7, // 1: common.PodStatus.created:type_name -> google.protobuf.Timestamp
	4, // 2: common.WorkspaceStatus.pod_status:type_name -> common.PodStatus
	7, // 3: common.WorkspaceInfo.deployed:type_name -> google.protobuf.Timestamp
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_gapi_common_proto_init() }
func file_pkg_gapi_common_proto_init() {
	if File_pkg_gapi_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_gapi_common_proto_rawDesc), len(file_pkg_gapi_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_gapi_common_proto_goTypes,
		DependencyIndexes: file_pkg_gapi_common_proto_depIdxs,
		MessageInfos:      file_pkg_gapi_common_proto_msgTypes,
	}.Build()
	File_pkg_gapi_common_proto = out.File
	file_pkg_gapi_common_proto_goTypes = nil
	file_pkg_gapi_common_proto_depIdxs = nil
}
